version: '3'

services:

  app:
    image: qidang/4640-app:latest
    ports:
      - 5000:5000

  web:
    image: qidang/4640-web:latest
    environment:
      API_URL: "http://app:5000"
    ports:
      - 3000:80
