name: 4640-docker-inclass

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          tags: qidang/4640-app:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: html
          push: true
          tags: qidang/4640-web:latest
